### PR TITLE
bug in matching elements by text

### PR DESCRIPTION
**Pull request by titusfortner**
DO NOT COMMIT - This is an example of the bug described in https://github.com/watir/watir-webdriver/issues/336

### CODE REVIEW

**Comment by p0deje** [comment]
If you locate the `th` or the `tr` and call `.text` on them - they both will return "March 2008":

```irb
irb(main):005:0> driver.find_elements(xpath: './/*[normalize-space()="March 2008"]').map &:text
=> ["March 2008", "March 2008"]
```

The way it works is that it should return all elements, which text equals "March 2008", so I don't really see a problem here.

Since HTML is hierarchical, it is correct that parent text includes children text.

**Comment by titusfortner** [comment]
Ok, this now is updated for https://github.com/watir/watir-webdriver/issues/337 
I'm ok with multiple matches if we're using regex, but exact text seems like it should be a one-to-one matching.
Was multiple element matches an issue in watir-classic? @bret @jkotests ?

**Comment by jkotests** [comment]
I am pretty sure that matching against all of the descendent text nodes has been the behaviour in Watir-Classic for a long time. 

For an HTML like:

````````
<div>April <strong>23,</strong> 2015</div>
```````

Are you suggesting that locating the div by its text would only include its immediate child text nodes:

````````
browser.div(text: 'April 2015')
```````

That seems a bit odd to me, especially given that you are not suggesting that the same change be made to the Element#text method.

I would prefer to keep the existing behaviour, ie `browser.div(text: 'April 23, 2015')`. While there have been questions about getting only the immediate child text nodes, I have not seen a strong use case.

**Comment by p0deje** [comment]
:+1: to what @jkotests said. If we change the behavior, that would actually be less expected, because our current implementation is consistent with other technologies. For instance, DOM works the same way:

```javascript
> document.getElementsByTagName('div')[0].innerText
"April 23, 2015"
```

**Comment by bret** [comment]
Multiple element matches have been a long-time feature of watir.

**Comment by titusfortner** [comment]
Hmm, I guess the specific use case that seems especially "bad" to me is when you have this:
```HTML
<div>
    <a href="http://google.com">Link Text</a>
</div>
```
These don't work:
```Ruby
browser.element(text: "Link Text").click
browser.element(text: /Link Text/).click
```
Of course this works:
```Ruby
browser.link(text: "Link Text").click
```
But what if the element isn't a link? Or, even better, what if you need to click a div that is nested in another div?
```HTML
<div>
    <div onclick="this.innerHTML = 'Onclick works!'">
        Onclick Element
    </div>
</div>
```
With the current code, you *can't do it. I would expect both of these to work, but neither does:
```Ruby
browser.element(text: "Onclick Element").click
browser.div(text: "Onclick Element").click
```

Also, I totally get it, calling #text on any element gives you all of the innerHTML. To the example @jkotests provided, with the code I proposed, this is what would match it (and I agree that it isn't ideal):
```Ruby
browser.div(text: "April")
```
But your selector is misleading, because you can't actually interact with the element if you need to. The selector matching is only good for validating text, and at that point, we might as well be using nokogiri.

This highlights another big bug with this approach:
```HTML
<div> <div style="display: none" value="bar">April <strong>23, </strong>2015</div>
</div>
```
These will *incorrectly return a true value:
```Ruby
browser.element(text: "April 23, 2015").present? # => True, should be false
browser.div(text: "April 23, 2015").present? # => True, should be false
```
Interestingly, our Regex implementation returns the incorrect value the other way, because it is looking at Selenium's #text call, which does not include anything that is hidden:
```Ruby
browser.element(text: "April 23, 2015").exists? # => False, should be true
browser.div(text: "April 23, 2015").exists? # => False, should be true
```
The Pull Request referenced would fix the incorrect String response, but not the incorrect Regex response.

This might be the wrong fix for these issues, but these are real bugs that need to be addressed in some fashion, even if it breaks backward compatibility to an extent. Actually, maybe if we solved [Issue #239](https://github.com/watir/watir-webdriver/issues/329), it would also fix these issues. I do think we need to find a solution if we consider text matching to be one of the bigger advantages of Watir over straight Selenium, and we want to encourage more usage of Watir.

**Comment by jkotests** [comment]
What version of Watir-Webdriver were you using when you got:
```````
browser.element(text: "April 23, 2015").exists? # => False, should be true
browser.div(text: "April 23, 2015").exists? # => False, should be true
```````
I ran this with v0.7.0 and they both returned true.

**Comment by p0deje** [comment]
It is definitely a problem that string and regexp implementations return different results, though I'm not sure how can it be fixed. One possible solution is to convert regexps to XPath (but it won't be working in 100% of cases), another solution is to change `#text` calls to JS `#innerText`. I am not sure about any of these, just some random ideas. I guess we should just extract a bunch of bugs from the examples and move on trying to fix them.

Anyways, I'm still sure that we should not change current implementation to match the exact containing element because it is:

* consistent behavior across different tools (javascript, query languages)
* much more flexible
* existed for a long time

Changing the behavior will also require a lot of users to update their tests for no good. We haven't seen a bunch of requests to change it, so why should we do that?

P.S. The point of "nested divs" is actually a question of application testability (i.e. this is not testable layout both for system tests (e.g. watir) or integration tests (e.g. javascript tests).

**Comment by titusfortner** [comment]
@jkotests I was using master, but I verified it with v0.7. here's a better copy/paste html-
```HTML
<body>
<div>
    <div style="display: none" value="bar">
        April <strong>23, </strong>2015
    </div>
</div>
</body>
````
Our current text matching with xpath implementation returns the outermost div that contains the desired match. Watir is verifying that the outer tag is visible, even if what we actually want to match nested beneath it is not. Interestingly if you call #text on that element, it properly returns an empty string.

**Pull request closed without merging**
