### PR TITLE
No watir classic guards

### PR DESCRIPTION
**Pull request by titusfortner**
Updates :watir_classic and :webdriver references in the guards. This does not change the now-unnecessary `WatirSpec#implementation` code to reflect webdriver-only implementation. 

@p0deje I can start hacking on that second part, but at some point I'll need help, and it might make more sense to come up with a better overall spec implementation, now that everything running these specs will be webdriver-based.

### CODE REVIEW

**Comment by p0deje** [comment]
Do you really think we need to get rid of `WatirSpec#implementation`? It's very simple and allows watirspec users to override the default implementation.

That's an implementation watizzle uses:

```ruby
WatirSpec.implementation do |watirspec|
  watirspec.name = :watizzle
  watirspec.browser_class = Watir::Browser
  watirspec.browser_args = [:firefox, {}]
  watirspec.guard_proc = lambda do |args|
    args.any? do |arg|
      [
        :webdriver,
        :firefox,
        %i[webdriver firefox]
      ].include?(arg)
    end
  end
end
```

**Comment by p0deje** [comment]
:+1: on this PR

**Comment by titusfortner** [comment]
I don't understand its purpose if everything using Watirspec is webdriver based. It might make more sense if I saw what you were doing with watizzle, but I guess for now it doesn't matter, since this is a lower priority that everything else we are working on right now. Thanks.

**Comment by p0deje** [comment]
I think a great example is when we allow (as we discussed on bazaar) the extensions through composition as arguments to `Watir::Browser` constructor, e.g.:

```ruby
WatirSpec.implementation do |watirspec|
  watirspec.name = :watir_enabler
  watirspec.browser_class = Watir::Browser
  watirspec.browser_args = [:firefox, {listener: WatirEnabler.new}]
end
```

**Pull request merged**
