### PR TITLE
spec for race condition with slow loading iframes

### PR DESCRIPTION
**Pull request by titusfortner**
This is the spec for [this pull request](https://github.com/watir/watir-webdriver/pull/317)
This test isn't ideal because it doesn't actually fail with current code, even though I think it is the right way to verify the code in the above pull request.

### CODE REVIEW

**Comment by p0deje** [comment]
We definitely need to make the test fail on current implementation, otherwise there is no point in it since it wouldn't catch possible regression.

I believe stubbing `IFrame#all_elements` to return empty array should be enough to reproduce the bug.

**Comment by titusfortner** [comment]
I've tried this a bunch of ways, and can't figure out how to make this work. Firstly, the original code defined all_elements inside another method call, instead of it being it's own method. I'm sure there is a way to mock that out, I couldn't figure it out. Secondly, even if I could, setting all_elements to return an empty array wouldn't pass on the new implementation, because the important piece is that the second call (regardless of #elements vs #all_elements) returns more elements than the original call, so what we would need is to determine which call was first and set that one to return an empty array.

Creating specs for race conditions is somewhat counterintuitive to me, because it does more than just specify the expected behavior of the app, it relies on mocking out implementation details to force the condition. I'm not sure this test actually provides useful information about the code.

**Comment by jkotests** [comment]
Would it make more sense for this test to be in the Watir-Webdriver project rather than Watirspec? `ElementLocator` is an internal API that may not be implemented in all projects using this spec. For example, it does not exist in Watir-Classic.

**Comment by p0deje** [comment]
@jkotests That could have been part of watirspec if we could make it black-box, but since the only way to write such test is mocking, let's not do that in watirspec.

@titusfortner I'm closing this and will try to write the spec failing. If it doesn't work out, let's just merge a fix with a comment in code.

**Comment by p0deje** [comment]
@titusfortner I've pushed comment, let's not write spec as you propose.

**Comment by titusfortner** [comment]
I agree with this. Thanks.

**Pull request closed without merging**
